### ISSUE TITLE
Devel has been removed from homebrew

### ISSUE THREAD

**Issue by Zialus** [joelpurra/homebrew-joelpurra#3]
```
Error: Failed to import: /usr/local/Homebrew/Library/Taps/joelpurra/homebrew-joelpurra/gitslave.rb
gitslave: undefined method `devel' for #<Class:0x00007fad64832020>
Error: Failed to import: /usr/local/Homebrew/Library/Taps/joelpurra/homebrew-joelpurra/jq.rb
jq: undefined method `devel' for Formulary::FormulaNamespaceda09b8f19e4d98dec5da196f1b67b3aa::Jq:Class
Error: Failed to import: /usr/local/Homebrew/Library/Taps/joelpurra/homebrew-joelpurra/jqnpm.rb
jqnpm: undefined method `devel' for #<Class:0x00007fad648509a8>
```

**Comment by joelpurra** [comment]
@Zialus: ah, yes. Looked at this a while ago, but for whatever reason the fixes didn't pass auditing then -- but they did now.

```shell
brew audit --fix --strict --online ./*.rb
```

Replaced `devel` blocks with `head`, audited, fixed, and pushed just now. Thanks for reminding me!

---

Had to make some additional changes to the `gitslave` and `jq` forks. Seems `--HEAD` (`:head` in formulas) doesn't work as expected, so removed the `head` blocks for forks altogether.

In addition, presumably because I'm still running macOS 10.14.6 (Mojave), I get errors about "A newer Command Line Tools release is available." (but sometimes just warnings) so could not confirm that all formulas work as expected. Hopefully this is not an issue on newer macOS versions.
